spring.application.name=management
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.pattern.level="%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management.endpoints.web.exposure.include=health,info,promotheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
management.metrics.export.promotheus.enabled=true

server.port=8081

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=my-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
